### ISSUE TITLE
Kopier sesong - ønske om ny funksjonalitet

### ISSUE THREAD

**Issue by sigurdne** [PorticoEstate/PorticoEstate#1128]
Etter eit møte i går, vart det spørsmål om å få eit estimat på kor lang tid det vil å få laga ein "Kopier sesong"-knapp.

Vedlagt lysark viser kor knappen skal vere (ark 2) og kva knappen skal gjere (detaljar i ark 3, 4 og 5)

Ark 3 og 4 saknar vi i tillegg ein "Lagre"-knapp, og 
litt luksus med ein "Ny interntildeling-knapp" i ark 4 (men dette er IKKJE viktig i denne omgang.

Ark 6 har to ekstra ønsker; større popup vindu og Pris=0

[Kopier sesong- backend.pptx](https://github.com/PorticoEstate/PorticoEstate/files/4422397/Kopier.sesong-.backend.pptx)

**Comment by ragnarbu** [comment]
Fornya bestilling - epost til Sigurd den 7.jan 2021 - denne oppgåva inngår i topp 10 saker prioritert av Brukarforum Aktiv kommune vår 2021.
