### ISSUE TITLE
ST1 - uleselig tekst i autogenerert epost svar. Link til arrangement fungerer ikke

### ISSUE THREAD

**Issue by geirsandvoll** [PorticoEstate/PorticoEstate#1312]
Når autogenerert e-post under vert sendt ut til brukarar ser den slik ut. Er det mogleg å gjere denne e-posten meir oversiktleg? I tillegg fungerer ikkje lenkja som er lagt ved i e-posten. Det kjem opp at sida ikkje vert funnen. 

"xxxxxxxxx har fått innvilget et arrangement i Radøyhallen (Radøyhallen fleirbrukshall sal A &#40;sal 1 frå høgre&#41;, Radøyhallen fleirbrukshall sal B &#40;sal 2 frå høgre&#41;, Radøyhallen fleirbrukshall sal C &#40;sal 3 frå høgre&#41;, Radøyhallen fleirbrukshall sal D &#40;sal 4 frå høgre&#41;) 14/11/2020 12:00 - 14/11/2020 22:00.
Link til Aktiv kommune Alver"

**Comment by sigurdne** [comment]
Er denne fortsatt aktuell?

**Comment by geirsandvoll** [comment]
Denne mener jeg ble fikset ikke så lenge etter den ble rapportert inn 😊

Med vennlig hilsen
Geir Sandvoll Andersen
Rådgiver Innbyggerdialog
Innbygger- og samfunnskontakt
Tlf. 992 95 080

Fra: Sigurd Nes <notifications@github.com>
Sendt: mandag 8. mars 2021 09:59
Til: PorticoEstate/PorticoEstate <PorticoEstate@noreply.github.com>
Kopi: Geir Sandvoll Andersen <geir.sandvoll.andersen@stavanger.kommune.no>; Author <author@noreply.github.com>
Emne: Re: [PorticoEstate/PorticoEstate] ST1 - uleselig tekst i autogenerert epost svar. Link til arrangement fungerer ikke (#1312)


Er denne fortsatt aktuell?
