### ISSUE TITLE
Bet 2 Saksbehandler må kunne bestemme om betaling kan skje via nett

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/PorticoEstate#1320]
Som saksbehandler må jeg kunne bestemme om en ressurs skal være mulig å betale for via nett(eksempelvis vipps)

For mindre anlegg, rom som er egnet for kortidsleie(likt kino, tennishall, øvingslokale), så må det være mulig for saksbehandler å bestemme timepris og om den skal aktiveres for ressursen.

**Comment by geirsandvoll** [comment]
> Som saksbehandler må jeg kunne bestemme om en ressurs skal være mulig å betale for via nett(eksempelvis vipps)
> 
> For mindre anlegg, rom som er egnet for kortidsleie(likt kino, tennishall, øvingslokale), så må det være mulig for saksbehandler å bestemme timepris og om den skal aktiveres for ressursen.

Ønsker at saksbehandler skal kunne bestemme hvilke betalingsløsninger som burde vært tilgjengelig.
