### ISSUE TITLE
Bet 7 Det må være mulig å kreve inn moms på utleien

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/PorticoEstate#1325]
Enkelte ressurser må kunne leies ut med momsinnkreving. 
Andre leieforhold går uten moms.
(og noen leieforhold er gratis - ingen betaling kreves)

**Comment by geirsandvoll** [comment]
> Enkelte ressurser må kunne leies ut med momsinnkreving.
> Andre leieforhold går uten moms.
> (og noen leieforhold er gratis - ingen betaling kreves)

Konfigurerbar momssats
