### ISSUE TITLE
Blokkere samtidige søknader ved å opprette reservasjon

### ISSUE THREAD

**Issue by sigurdne** [PorticoEstate/PorticoEstate#1447]
Når en velger en ressurs og en tidsluke - må systemet blokkere andre forsøk på dobbelbooking
- opprette en reserverasjon

**Comment by ragnarbu** [comment]
Denne er viktig å få ordna opp i - både Sandnes og Bergen har opplevd at innbyggarar på same tid har gått inn og søkt på same leigeobjekt og leigeperiode, og det har oppstått "dobbel-reserveringar/bookingar". Og som det har teke tid å rydde opp i.
