### ISSUE TITLE
Problem med dato/tid-veljar for tildelingar, interntildelingar

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/PorticoEstate#1453]
Denne saka inngår i opp 10- prioriteringar bestemt av Brukarforum Aktiv kommune - for våren 2021:
(epost er sendt til Sigurd den 7.jan 2021)

I fleire skjema i Aktiv kommune (for det meste backend, men også frontend), så opplever sakshandsamar at det å registrere inn «frå dato/klokkeslett» og «til dato/klokkeslett» vert unødvendig mange klikk og justeringar på. Desse bør det rettast på – (alle er kvikk-vinn).
Dette gjeld spesielt for 
-	NYE (opprettelse) av tildelinger, arrangementer og interntildelinger, men også for –
-	ENDRINGER i eksisterende tildelinger, arrangementer og interntildelinger.

Eksempel er omtala i vedlegget "Nokre unødvendige datokrøllar - jan 2021 v2.docx"
[Nokre unødvendige datokrøllar  - jan 2021 v2.docx](https://github.com/PorticoEstate/PorticoEstate/files/5848437/Nokre.unodvendige.datokrollar.-.jan.2021.v2.docx)

**Comment by sigurdne** [comment]
Prøv no (master-branch)
