### ISSUE TITLE
Front end kalender

### ISSUE THREAD

**Issue by geirsandvoll** [PorticoEstate/PorticoEstate#1503]
Når vi holder musepekeren over en kalenderøkt i front end, og så tar den vekk til en ledig tid, så ligger pop up informasjon der helt til du velger å dra musepekeren over en ny kalenderøkt. 
![Skjermbilde](https://user-images.githubusercontent.com/67580066/108357853-4775f500-71ee-11eb-8ec6-cd50db52f72f.JPG)

Er det mulig å endre det slik at denne pop up informasjonen forsvinner når du fjerne musepekeren vekk fra den lille bulken i kalenderen? 

Forståelig? Hvis ikke så gjerne spør.

**Comment by sigurdne** [comment]
Ny frontend er på veg
