### ISSUE TITLE
Research på velge tid i kalender på mobil

### ISSUE THREAD

**Issue by ArildR82** [PorticoEstate/PorticoEstate#2452]
**Beskrivelse**
Finne en god løsning på hvordan brukere som benytter mobil til booking kan klikke i kalender og dra for å velge tidspunkt. 

**Utfordring**
En bruker bruker drag for å navigere opp og ned på en side når han er på mobil.

**Comment by flogvit** [comment]
Inntil videre lager vi det slik at når man klikker i kalenderen på mobil så vil den gå direkte videre til booking siden med avsatt 1 time på en ressursen. Så kan brukeren selv velge å utvide. Dette blir gjort under #2420 oppgaven
