### ISSUE TITLE
Ta med info fra landingsside til søknad

### ISSUE THREAD

**Issue by ArildR82** [PorticoEstate/PorticoEstate#2474]
**Beskrivelse**
Når jeg som søker har valgt leieobjekt og deretter klikker på søknad forventer jeg at leieobjektet er valgt. 

**Kommentar**
Når søker velger leieobjekt og klikker på søknad kommer de til søknadsskjema hvor "Ingen leieobjekt er valgt" Det bør fungere slik at systemet husker hvilket leieobjekt søker har valgt.

**Comment by flogvit** [comment]
Har lagt til resource_id i url slik at man kommer til korrekt leieobjekt.

**Comment by ArildR82** [comment]
Hei @flogvit Det er ønskelig at også ressursen man velger tas med videre til søknadsskjema, Nå tas ikke dette med videre. Det er også ønskelig å kunne velge flere ressurser.

**Comment by ArildR82** [comment]
Dersom man velger ett tidspunkt vil det tas med videre til søknadsskjema, men dersom man velger flere vil den bare ta med ett tidspunkt. dersom man velge flere rom/lokaler vil den fortsatt bare ta med den første tidspunktet du legger inn.

**Comment by ArildR82** [comment]
Får en av dere tid til å teste dette i dag @ragnarbu , @geirsandvoll ?
