### ISSUE TITLE
Får ikke skrudd på ny template

### ISSUE THREAD

**Issue by ArildR82** [PorticoEstate/PorticoEstate#2854]
**Beskrivelse**
Det mangler mulighet til å bytte til ny versjon i Kristiansand sin template i Edge nettleser.

![Image](https://github.com/PorticoEstate/PorticoEstate/assets/142302189/4065ac86-8f20-48c5-a936-451993c2bee5)

**Comment by geirsandvoll** [comment]
I adm.grensesnitt så må man sette på developmode. 

Administrasjon - Bookingfrontend - Konfiurasjon
Sett developmode på Ja.
