### ISSUE TITLE
Feil visning av ledig/opptatt på ressurs

### ISSUE THREAD

**Issue by ArildR82** [PorticoEstate/PorticoEstate#2992]
**Beskrivelse**

**Instants:** Stavanger

I gammel versjon så vises det opptatt de tidspunkt det er en interntildeling. I ny front så vises de som ledig. Regner med den nye kanskje ikke tar med tildelinger i disse slottene, bare arrangement. Se bilder. 

Nederste bilde viser fargeforskjell på at gjeldende tidspunkt er tildeling og ikke arrangement. 

![Image](https://github.com/PorticoEstate/PorticoEstate/assets/142302189/9019f4ef-5292-4e98-8481-74722e5fbcbd)

![Image](https://github.com/PorticoEstate/PorticoEstate/assets/142302189/1ce23a68-2a7e-449f-9ed9-90c26ec9acf4)

![Image](https://github.com/PorticoEstate/PorticoEstate/assets/142302189/0e9f3f0c-70f8-4547-8b76-e7f501df1a4a)

**Innemeldt av | dato**
Geir Sandvoll Andersen | Mai 2024

**Comment by ArildR82** [comment]
@geirsandvoll Kan du sjekke om denne er fikset og endre status til Ferdig eller feilet i test?

**Comment by geirsandvoll** [comment]
Ferdig. Første fiks var å gjøre den opptatt. Så viste tildeling gul reservert, som er samme farge/navn når noen er inne og booker. Nå vises tildeling som opptatt og ikke reservert. Fikset
